/*
 * generated by Xtext 2.24.0
 */
package fr.inria.kairos.tuto.simplelanguage.xtext;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class SmartContractMLRuntimeModule extends AbstractSmartContractMLRuntimeModule {
}
