/*
 * generated by Xtext 2.24.0
 */
package fr.inria.kairos.tuto.simplelanguage.xtext.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class SmartContractMLUiModule extends AbstractSmartContractMLUiModule {

	public SmartContractMLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
