/*
 * generated by Xtext 2.24.0
 */
package fr.inria.kairos.tuto.simplelanguage.xtext.web;


/**
 * Use this class to register additional components to be used within the web application.
 */
public class SmartContractMLWebModule extends AbstractSmartContractMLWebModule {
}
