/*
 * generated by Xtext 2.24.0
 */
package fr.inria.kairos.tuto.simplelanguage.xtext.parser.antlr;

import com.google.inject.Inject;
import fr.inria.kairos.tuto.simplelanguage.xtext.parser.antlr.internal.InternalSmartContractMLParser;
import fr.inria.kairos.tuto.simplelanguage.xtext.services.SmartContractMLGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class SmartContractMLParser extends AbstractAntlrParser {

	@Inject
	private SmartContractMLGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalSmartContractMLParser createParser(XtextTokenStream stream) {
		return new InternalSmartContractMLParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "SmartContract";
	}

	public SmartContractMLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(SmartContractMLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
