/*
 * generated by Xtext 2.24.0
 */
package fr.inria.kairos.tuto.simplelanguage.xtext.ui.tests;

import com.google.inject.Injector;
import fr.inria.kairos.tuto.simplelanguage.xtext.ui.internal.XtextActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class SmartContractMLUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return XtextActivator.getInstance().getInjector("fr.inria.kairos.tuto.simplelanguage.xtext.SmartContractML");
	}

}
