/*
 * generated by Xtext 2.24.0
 */
package fr.inria.kairos.tuto.simplelanguage.xtext.ide;


/**
 * Use this class to register ide components.
 */
public class SmartContractMLIdeModule extends AbstractSmartContractMLIdeModule {
}
