/*
 * generated by Xtext 2.24.0
 */
package fr.inria.kairos.tuto.simplelanguage.xtext.web;

import org.eclipse.xtext.web.server.DefaultWebModule;

/**
 * Manual modifications go to {@link SmartContractMLWebModule}.
 */
@SuppressWarnings("all")
public abstract class AbstractSmartContractMLWebModule extends DefaultWebModule {

}
